# Generated by Django 5.1.5 on 2025-01-22 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='cryptocurrency',
        ),
        migrations.CreateModel(
            name='WalletCrypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('cryptocurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.cryptocurrency')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cryptos', to='transactions.wallet')),
            ],
            options={
                'unique_together': {('wallet', 'cryptocurrency')},
            },
        ),
    ]
